version: "3.9"
networks:
  timmy_network:
      name: timmy_network
      external: true

services:
  ta-tomcat:
    image: "toolapp-axelor/tomcat:0.0.1"
    container_name: ${INSTANCE_NAME}_tomcat
    build:
      context: "./00_TOMCAT"
    volumes:
      #- "./docker-entrypoint.d:/tmp/docker-entrypoint.d"
      #- "./docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh"
      - "./00_TOMCAT/axelor-config.properties:/usr/local/tomcat/axelor-config.properties:ro"
      #- "./XX_DATA/var/lib/tomcat:/var/lib/tomcat"
      #- "./XX_DATA/var/log/tomcat:/var/log/tomcat"
      #- "./XX_DATA/usr/local/tomcat/upload:/usr/local/tomcat/upload"
      ###- "./XX_DATA/usr/local/tomcat/reports:/usr/local/tomcat/reports"
      #- "./XX_DATA/usr/local/tomcat/data-export:/usr/local/tomcat/data-export"
      ##- "./XX_DATA/usr/local/tomcat/logs:/usr/local/tomcat/logs"
      #- "./XX_DATA/usr/local/tomcat/reports-gen:/usr/local/tomcat/reports-gen"
      #- "./XX_DATA/usr/local/tomcat/templates:/usr/local/tomcat/templates"
      #- "./XX_DATA/usr/local/tomcat/temp:/usr/local/tomcat/temp"
    restart: always
    environment:
      - JAVA_OPTS= "-Daxelor.config=/usr/local/tomcat/axelor-config.properties"
      # pour nginx proxy
      - VIRTUAL_HOST=${INSTANCE_HTTP}
      #- VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${INSTANCE_HTTP}
#      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
      - DB_HOST=psql
      - DB_PORT=5432
      - DB_NAME=${INSTANCE_NAME}_axr
      - DB_USER=timmy
      - DB_PASSWORD=Toolapp44119!
    networks:
      - timmy_network
